Fluent Connections/Controllers/DeviceManagerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Fluent_Connections.Data;
using Fluent_Connections.Models.DataModels.Account;
using Fluent_Connections.Models.DataModels.JoinModels;
using Fluent_Connections.Models.ViewModels.IoT;
using Fluent_Connections.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Fluent_Connections.Controllers
{

    [Authorize]
    public class DeviceManagerController : Controller {

        private readonly ApplicationDbContext _dbContext;
        private readonly AppUserRepository _appUserRepository;
        private readonly IoTSystemRepository _iotSystemRepository;
        private readonly HttpClient _client = new HttpClient();

        public DeviceManagerController(ApplicationDbContext dbContext,
                UserManager<AppUser> userManager,
                SignInManager<AppUser> signInManager) {

            _dbContext = dbContext;

            _appUserRepository = new AppUserRepository(dbContext,
                userManager, signInManager);

            _iotSystemRepository = new IoTSystemRepository(dbContext);
        }

        public IActionResult Index() {
            /*StandardUser user = (StandardUser) await _appUserRepository.GetUserAsync(User);

            user.Initialise();

            user.ClientDevices.get*/

            return View();
        }

        public async Task<IActionResult> AddBluetoothDevices(
                [FromBody] SelectedBeaconDeviceViewModel[]
                selectedBeaconDevices) {

            //NEED TO HANDLE WHEN USER IS NOT STANDARD USER
            StandardUser standardUser = (StandardUser)
                await _appUserRepository.GetUserAsync(User);

            foreach(SelectedBeaconDeviceViewModel selectedBeaconDevice
                    in selectedBeaconDevices) {

                BeaconDevice beaconDevice = BeaconDevice.CreateBeaconDevice(
                    selectedBeaconDevice);

                await _iotSystemRepository.AddBeaconDeviceAsync(
                    beaconDevice);

                string clientDeviceId = selectedBeaconDevice.ClientDeviceId;

                ClientDevice clientDevice = (ClientDevice) await
                    _appUserRepository.GetUserFromIdAsync(clientDeviceId);

                BeaconClientDevice beaconClientDevice =
                    new BeaconClientDevice(clientDevice, beaconDevice);

                await _iotSystemRepository.AddBeaconClientDeviceAsync(
                    beaconClientDevice);

                UserBeaconDevice userBeaconDevice = new UserBeaconDevice(
                    beaconDevice.Name, "", standardUser, beaconClientDevice);

                await _appUserRepository.AddUserBeaconAsync(userBeaconDevice);
            }

            return Ok();
        }

    }
}

Fluent Connections/Views/DeviceManager/Index.cshtml
@{
  ViewData["Title"] = "Index";
}

<h2 class="common-heading">Discovered Devices</h2>

<script src="~/lib/signalr/signalr.js"></script>
<script src="~/scripts/SecurityLib.js"></script>
<script src="~/scripts/ReactionDisplay.js"></script>

<script>
  function createNewDiscoveredDevice(device) {
    var name = device.name;
    var modelNumber = device.modelNumber;
    var serialNumber = device.serialNumber;
    var address = device.address;
    var type = device.type;
    var clientDeviceId = device.clientDeviceId;

    var textName = htmlEncode(name);
    var textType = htmlEncode(type);

    return (
      "<div class='device-option-btn option-unselected' id='"
      + modelNumber + serialNumber + "' data-name='" + textName
      + "' data-model-number='" + modelNumber
      + "' data-serial-number='" + serialNumber
      + "' data-address='" + address
      + "' data-client-device-id='" + clientDeviceId + "'>" +
      " <div class='device-name device-option-contents'>"
        + textName + "</div>" +
      " <div class='vl iot-option-contents'></div>" +
      " <div class='device-type device-option-contents'>"
        + textType + "</div>" +
      "</div>");
  }
</script>

<div id="discovered-devices">

</div>

<p class="common-info-text" id="scanning-text">Scanning For Devices</p>

<div class="horizontal-choice">
  <button class="choice-btn" id="cancel-device-selection">
    Cancel
  </button>
  <button class="choice-btn" id="confirm-device-selection">
    Add Selected
  </button>
</div>

<script>
  var scanningText = $("#scanning-text");
  var discoveredDevices = $("#discovered-devices");
  var cancelSelection = $("#cancel-device-selection");
  var confirmSelection = $("#confirm-device-selection");
  var numOfSelectedDevices = 0;

  confirmSelection.addClass("hide-block-button");

  dotTimer = dotText(scanningText);

  const connection = new signalR.HubConnectionBuilder()
    .withUrl("/devicesHub")
    .configureLogging(signalR.LogLevel.Information)
    .build();

  connection.start().then(function () {
    connection.stream("ScanForDevices")
      .subscribe({
        next: (device) => {
          var d = createNewDiscoveredDevice(device);

          discoveredDevices.append(d);
        },
        complete: () => {
          clearInterval(dotTimer);
          scanningText.text("Complete");
        },
        error: (err) => {
          clearInterval(dotTimer);
          scanningText.text("Scanning failed to complete");
        }
      });
  });

  onDeviceChosen = function () {
    numOfSelectedDevices++;

    if (numOfSelectedDevices == 1) {
      confirmSelection.removeClass("hide-block-button")
        .addClass("show-block-button");
    }
  }

  onDeviceUnchosen = function () {
    numOfSelectedDevices--;

    if (numOfSelectedDevices == 0) {
      confirmSelection.removeClass("show-block-button")
        .addClass("hide-block-button");
    }
  }

  makeComponentsChoosable(discoveredDevices, ".device-option-btn",
    onDeviceChosen, onDeviceUnchosen);

  cancelSelection.click(function () {
    window.location.href = "@Url.Action("Index", "Home")";
  });

  confirmSelection.click(function () {
    var selectedDevices = $(".option-chosen");

    var devices = selectedDevices.map(function () {
      var device = new Object();

      device.name = $(this).attr("data-name");
      device.modelNumber = $(this).attr("data-model-number");
      device.serialNumber = $(this).attr("data-serial-number");
      device.address = $(this).attr("data-address");
      device.clientDeviceId = $(this).attr("data-client-device-id");

      return device;
    }).get();

    $.ajax({
      type: "POST",
      url: "@Url.Action("AddBluetoothDevices", "DeviceManager")",
      contentType: "application/json; charset=utf-8",
      data: JSON.stringify(devices),
      success: function () {
        window.location.href = "@Url.Action("Index", "Home")";
      },
      error: function () {
        alert("Failed to add devices");
      }
    });
  });
</script>

@*<script>
    $(document).ready(function () {
      $.ajax({
        type: "GET",
        url: '@Url.Action("ScanDevices", "DeviceManager")',
        success: function (devices) {

        },
        error: function () {
          alert("Failed to scan devices");
        }
      });
    });
  </script>*@